### ISSUE TITLE
虽然还没读，不过《云球》的简介怎么那么像《刀剑神域 Alicization》呢？

### ISSUE THREAD

**Issue by linonetwo** [MrQianJinSi/weekly-readings#1]
都是「研究所运营着计算机虚拟世界xx。运营了十年后，云球上产生了人类社会并达到了农业时代，但是此时演化却出现了停滞现象」

**Comment by MrQianjinsi** [comment]
我没看过刀剑神域，听你这么描述确实挺像的。不过云球里面人和电子人可以互换意识，还挺好玩的。

lin onetwo <notifications@github.com> 于2019年5月3日周五 上午12:10写道：
